version: '3.7'

services:
  app:
    build : './app'
    ports:  
      - "8080:8080"
    
  rabbitmq:
    hostname: rabbit
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "15672:15672"
      - "5672:5672"
  
  simple_worker:
    build: './simple_worker'
    user: nobody
    depends_on:
      - rabbitmq